Solve build issue with R 3.3.3 and gcc 10
- Missing 'extern' keyword in header file fails gcc 10 while linking:

"""
/usr/bin/ld: Rdynload.o:/tmp/build/d6b29ed3/r_src/R-3.3.3/src/main/../../src/include/Defn.h:1284: multiple definition of `R_OutputCon'; CommandLineArgs.o:/tmp/build/d6b29ed3/r_src/R-3.3.3/src/main/../../src/include/Defn.h:1284: first defined here
"""
  Use "-fcommon" to suppress it.

- Fortran compiling error with gcc10:

"""
cmplx.f:55915:56:
33404 |      $                        K, M-K, ONE, C( K+1, 1 ), LDC,
      |                                      2
......
55915 |                   CALL ZGEMM( 'N', 'N', N, IV, N-KI+IV, ONE,
      |                                                        1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/COMPLEX(8)).
"""
  Work around with "-fallow-argument-mismatch".